import React,{useEffect,useRef,useState} from 'react';
export function MusicPlayer({config}){
 const audio=useRef(null),[playing,setPlaying]=useState(false),[blocked,setBlocked]=useState(false),[error,setError]=useState('');
 useEffect(()=>{setPlaying(false);setBlocked(false);setError('');const node=audio.current;if(!node)return;node.volume=.5;if(config.musicAutoplay!==false)node.play().catch(e=>{if(e.name==='NotAllowedError')setBlocked(true);else if(e.name!=='AbortError')setError('No se pudo reproducir el audio. Revisá el archivo configurado.')});return()=>node.pause()},[config.musicAudioUrl,config.musicAutoplay]);
 if(!config.musicAudioUrl)return null;
 const play=()=>{const node=audio.current;if(!node)return;if(playing)node.pause();else{setError('');node.play().then(()=>setBlocked(false)).catch(()=>setError('No se pudo reproducir el audio. Revisá el archivo configurado.'))}};
 return <section className="site-player" id="music-player" aria-label="Reproductor de música"><div><small>{playing?'SONANDO AHORA':'LA SELECCIÓN DE DONT STOP'}</small><strong>{config.musicTitle||'Dont Stop'}</strong><span>{config.musicArtist}</span></div><button type="button" onClick={play} aria-label={playing?'Pausar música':'Reproducir música'}>{playing?'PAUSAR II':'REPRODUCIR ▶'}</button><audio ref={audio} id="site-audio" src={config.musicAudioUrl} loop preload="metadata" controls onPlay={()=>{setPlaying(true);setBlocked(false)}} onPause={()=>setPlaying(false)} onError={()=>setError('No se pudo cargar la canción. Revisá el enlace de audio.')} aria-label="Controles de música"/>{blocked&&<small className="player-note">Tocá REPRODUCIR para activar el sonido.</small>}{error&&<p className="form-error" role="alert">{error}</p>}</section>
}
export default function TbaPage({config}){
 const [email,setEmail]=useState(''),[name,setName]=useState(''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[sent,setSent]=useState(false),[error,setError]=useState('');
 async function subscribe(e){e.preventDefault();if(busy)return;setBusy(true);setError('');try{const r=await fetch('/api/subscribe',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,name,marketingConsent:consent})});const data=await r.json();if(!r.ok)throw new Error(data.error||'No se pudo guardar la suscripción.');setSent(true)}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <main className="tba-page"><div className="grain"/><header className="tba-head"><img className="brand-logo brand-logo-white" src="/brand/dontstop-red.png" alt="Dont Stop"/><span>{config.city}</span></header><div className="tba-layout"><section className="tba-message"><p className="eyebrow">LA PRÓXIMA NOCHE</p><h1>TBA<span className="tba-dot">.</span></h1><p className="tba-expansion">TO BE ANNOUNCED</p><p className="tba-description">Lo que viene todavía no tiene fecha.<br/>Vos podés ser el primero en enterarte.</p></section><section className="tba-subscribe"><h2>QUE NO TE LO CUENTEN.</h2><p>Dejá tu email y recibí novedades de nuestras próximas fiestas.</p>{sent?<div className="tba-success" role="status"><h3>SOLICITUD REGISTRADA ✓</h3><p>Gracias por formar parte de Dont Stop. Respetamos las bajas que hayas solicitado anteriormente.</p></div>:<form onSubmit={subscribe}><label>TU NOMBRE (OPCIONAL)<input maxLength="120" autoComplete="name" value={name} onChange={e=>setName(e.target.value)}/></label><label>TU EMAIL<input required type="email" maxLength="254" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="nombre@email.com"/></label><label className="tba-consent"><input required type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> Quiero recibir novedades y emails de Dont Stop.</label><button className="submit" disabled={busy}>{busy?'GUARDANDO…':'QUIERO ENTERARME ↗'}</button><small>Podés darte de baja desde cualquier campaña.</small>{error&&<p className="form-error" role="alert">{error}</p>}</form>}</section></div><MusicPlayer config={config}/><div className="tba-footer"><img className="brand-logo" src="/brand/dontstop-red.png" alt="Dont Stop"/><span>LA NOCHE CONTINÚA.</span></div></main>
}
